📝 Updated Czech localization
Crizz0/phpbb3-about-us pull request #52
Opened 2020-01-18 16:41 UTC by R3gi

Translated new strings, typography improvements, updated copyright year

Fixes: #51

2020-01-18 19:13 UTC, Crizz0 requested changes

2020-01-18 19:13 UTC, Crizz0 commented on language/cs/common.php
> +	'ACP_ABOUTUS_ENABLE_EXPLAIN'	=> 'Pokud není stránka „O nás“ povolena, nebude v zápatí fóra zobrazen odkaz pro její otevření. Nicméně prostřednictvím URL adresy „app.php/aboutus“ je možné stránku „O 
No space at the end needed

2020-01-20 12:12 UTC, R3gi commented on language/cs/common.php
> +	'ACP_ABOUTUS_ENABLE_EXPLAIN'	=> 'Pokud není stránka „O nás“ povolena, nebude v zápatí fóra zobrazen odkaz pro její otevření. Nicméně prostřednictvím URL adresy „app.php/aboutus“ je možné stránku „O 
Fixed, thanks!

2020-01-20 21:24 UTC, Crizz0 approved these changes

2020-01-20 21:24 UTC, merged

2020-01-20 21:25 UTC, Crizz0 commented
Thank you 👍